Guess_the_number.py
=> Added a guess the number game

binary_search.py
Hey, this is my first try to contribute to open source. I have added a binary search program for the python folder.
=> Added Binary Search File

TicTacToe.py
Thanks in advance for accepting my Pull Request..
I am willing to tell my parents that a coding can also help me to make my future and earn particularly.
By getting that T-Shirt, my parents will gonna think about lit a bit that what am I saying 'It can be possible'
Thanks again bro for your support
Saksham Dutt
=> TicTacToe Application

primeornot.py
This program tells if the input number is a prime number or not.
=> Program to tell if a number is prime or not.

Emoji_Convertor.py
This will help you gonna to convert specific keyboard symbol to the desire emoji
=> emoji convertor

Tic Tac Toe Game.py
I have subscribed your channel!!
=> Amazing Tic Tac Toe Game!!

simplecalculator.py
This is a simple calculator which can add, subtact, multiply and divide.
=> Program to Make a Simple Calculator

evenandodd.py
This program tells whether your number is even or odd
=> Added the even and odd number program

Longest_Substring_Without_Repeating_Characters.py
Given a string s, find the length of the longest substring without repeating characters.
Example 1:
Input: s = "abcabcbb"
Output: 3
Explanation: The answer is "abc", with the length of 3.
Example 2:
Input: s = "bbbbb"
Output: 1
Explanation: The answer is "b", with the length of 1.
Example 3:
Input: s = "pwwkew"
Output: 3
Explanation: The answer is "wke", with the length of 3.
Notice that the answer must be a substring, "pwke" is a subsequence and not a substring.
Example 4:
Input: s = ""
Output: 0
Constraints:
0 <= s.length <= 5 * 104
s consists of English letters, digits, symbols and spaces.
=> Added Longest_Substring_Without_Repeating_Characters.py

lcm2number.py
Python Program to find the L.C.M. of two input number
=> Python Program to find the L.C.M. of two input number

binaryrecursion.py
You can also change dec to get different values.
=> Function to print binary number using recursion

fibonaccisequence.py
To test the program, change the value of nterms.
=> Python program to display the Fibonacci sequence

palindromestring.py
To test the program, change the value of my_str in the program.
=> Program to check if a string is palindrome or not

Longest_Common_Subsequence.py
Finding Longest Common Subsequence between two string and display its length.
=> Find Longest Common Subsequence between two string

Random_Passwprd_Gen.py
This returns password of various types randomly generated
=> Added Random_Password_Gen.py

codestar.py
This is amazing clock like real clock you can try this thanks...
=> Added the codestar program

Jarvis.py
This is the amazing program. This Python personal assistant  will properly teach you how to create J.A.R.V.I.S with Python which is a Voice Activated Desktop Assistant. This Python AI virtual Assistant Tutorial will get you kick started and move towards the world of AI and ML.
=> Added the Jarvis program

Pavillion.py
DRS review system is a very popular technology in cricket with a good amount of Python logic to implement which makes this video a good source of logic building in Python. This technology is used in cricket world cup, IPL and international test cricket. This Third umpire toolkit in python gets easy to implement with this awesome
=> Added the Pavillion program

TEXT TO SPEECH.py, applicationopener.py
This app helps to open applications easily
=> applicationopener.py

Python Program to Multiply Two Matrices
created a pogram for multiplication of matrices taking user input
=> Create Python Program to Multiply Two Matrices

Fibonacci sequence
=> Create Fibonacci sequence

MooreVoting.py
=> Moore’s Voting Algorithm

AI upgrade-voices.py
here you able to modify default vioces in python programme.
=> Create AI upgrade-voices.py

speedtest.py
1.You Need to install speedtest -cli module.By "pip install speedtest -cli" or "pip3 install speedtest -cli".
2.Copy and paste this program and run it.
=> Added Speedtest Program

Polindrome using while loops
This program is made by using the while loop which checks the number is polindrome or not
=> Python Palindrome Program using While loop

Python Program for n-th Fibonacci number
Python Program for n-th Fibonacci Number
=> Create Python Program for n-th Fibonacci number

quadratic equation.py
I had added a program for quadratic equation.
=> Quadratic Equation program

Abhishek_Sahu
=> Abhishek Sahu Python PullRequest

Simple Calculator.py
Basic Calculator for addition, subtraction, multiplication and divide.
=> Added Simple Calculator Program

Leap Year.py
Here You can find the which year is leap year.
=> Added the Leap Year Program

Fibonacci Series-recursion.py
Created a Fibonacci series program using recursion
=> Fibonacci Series Program using recursion in python

Linear_search.py
Created a Linear Search Program in python
=> Linear Search.py

reversenumber.py
=> reversenumber.py

nationalflag.py
This is national flag program. Pls run it once and accept it. Jai Hind
=> nationalflag.py

Pig latin translator.py
=> Create Pig latin translator.py

sakshi.py, sakshi1.py
=> prime + factorial

Password_generator.py
Password Generator, it Generates one-time password Randomly
=> Added Password Generator

Dice_rolling_simulator.py
=> Added a Dice rolling simulator

Factorial_calculator.py
=> Added a Factorial calculator

Adventure_game.py
=> Added an Adventure game

magic number
=> Create magic number

duck number
=> Create duck number

kadane's algo
=> Create kadane's algo

stringpython.py
This python program includes string slicing, reversing
=> Added python program about string operations

Write a Python program to find the first appearance of the substring 'not' and 'poor' from a given string, if 'not' follows the 'poor', replace the whole 'not'...'poor' substring with 'good'. Return the resulting string. Go to the editor Sample String : 'The lyrics is not that poor!' 'The lyrics is poor!' Expected Result : 'The lyrics is good!' 'The lyrics is poor!'
Write a Python program to find the first appearance of the substring 'not' and 'poor' from a given string, if 'not' follows the 'poor', replace the whole 'not'...'poor' substring with 'good'. Return the resulting string. Go to the editor Sample String : 'The lyrics is not that poor!' 'The lyrics is poor!' Expected Result : 'The lyrics is good!' 'The lyrics is poor!'
=> python programs

Simple Calculator
This is a Python program for Simple Calculator by Using Functions.
In this program, we ask the user to choose an operation. Options 1, 2, 3, and 4 are valid. 
If any other input is given, Invalid Input is displayed and the loop continues until a valid option is selected.
=> Simple Calculator

Calculator.py
Simple Calculator by Using Functions
=> Simple Calculator by Using Functions

snakeladder
=> snake ladder game

paint.py
Paint game for drawing shapes.
How to play : 
1. Add a color.
2. Complete circle.
3. Complete rectangle.
4. Complete triangle.
5. Add width parameter.
=> Paint Game

word meaning.py
I have added a new project which will help you to find the meaning of word online
=> Added a new project to find word meaning

python pragramme of a maths calculator
please accept the pull request and merge
thank you  mayank for you support
=> python pragramme of a maths calculator

functions.py
=> functions.py

conditionals.js
=> conditionals.py

hourglass pattern
Python program to print hourglass pattern
=> Hourglass Pattern

flappy.py
Flappy, a game inspired by Flappy Bird.
How to play :+1: 
1. Keep score.
2. Vary the speed.
3. Vary the size of the balls.
4. Allow the bird to move forward and back.
=> Added Flappy Game

comparison operators.py
this is the code for comparison operators
=> code of comparison operators

geometric_progression.py
The program finds the sum of the given terms in the Geometric Progression
=> New program for G.P in python added geometric_progression.py

create a calendar with python
created a new file which contains program to create a calendar
=> create a new file program to make a calculator with python

Program to sort alphabetically the words form a string provided by the user.py
=> Program to sort alphabetically the words form a string provided by the user

Python Program to Find the Largest Among Three Numbers
this will help you to create best Python Program to Find the Largest Among Three Numbers.
=> Python Program to Find the Largest Among Three Numbers

Python Program to Check if a Number is Odd or Even
in this code you will be able to Python Program to Check if a Number is Odd or Even
=> Python Program to Check if a Number is Odd or Even

Fibonacci.py
Reverts codehouseindia/Python-Programs#57
=> Revert "Added the Fibonacci sequence Program"

Leap year
Added a Leap year program in python
=> Create Leap year

palindromeinbinaryrepresenation
Created program to check if binary representation of a number is palindrome.
=> BinaryPalindrome

sliding window problem
This is a program for sliding window problem in Python
=> Sliding window problem

python mask training
=> Create python mask training

fixing PIL issues in pytest output.py
Please accept and merge my pull request
=> Fixing PIL deprecation warnings in pytest output

Pacman using Python
=> Create Pacman using Python

Snake using Python
=> Create Snake using Python

palindromestring
Python program to check palindrome string
=> palindromestring

sort.py
Added python program of sorting.
=> Added a program of sorting

amazingoddnumber
=> amazingoddnumber

Square_of_a_number.py
This is basically a code in python to print square of a number
=> Added Square of a number program

palindromenum.py
Program for finding palindrome number using python
=> palindromenum.py

Fibonacci Series in Python
Program of Fibonacci series in python.
=> Added Fibonacci Series in Python

dfa_nfa.py
this is a theory of computation NFA (non-determinstic) to DFA(deterministic) automata
=> Added NFA to DFA Program

Anagram.py
Added code to check for anagrams
=> Added Code to check 2 strings are anagram ot not

Basic Socket/clint.py, Basic Socket/person.py, Basic Socket/server.py
Basic Example of connection between Clint and server
Server.py will create a server and n number of Clint can chat with each other
=> Example of Socket Connection

count_how_many days until a birthday.py
short script for counting how many days there is left for any given date
=> count days till birthday

data analysis using python
=> Create data analysis using python

Display Calendar
display the calendar of a given date in this example.
=> Display Calendar

Stooge Sort
=> Stooge Sort

Cycle Sort
=> Cycle Sort

graph_properties.py
This include python script to create and get basic information of a graph.
=> Create graph_properties.py - create and display graphs

Random-Password-Generator.py
Generate random password with following rules:
1. 6-20 characters
2. at least one uppercase character
3. at least one lowercase character
4. at least one digit
5. at least one special character (!, @, #, $, %, ^, &, *)
6. no more than 2 characters repeating consecutively
=> To help people in creating strong password

sumofevenandodd.py
its applicable to any number of any length......
=> added sum of even and odd digits in given number

NumberGuessing_1641017169.py
Number Guessing_Program by KumarSwaraj-1641017169
=> NumberGuessing_1641017169.py

text to speech.py
=> Create text to speech.py

Check Whether a String is Palindrome or Not
In this program. you'll learn to check whether a string is palindrome or Not
=> Check Whether a String is Palindrome or Not

krishnamurti number
=> added krishnamurti number

Area of triangle new
=> Create Area of triangle new

Square of number from 1 to n
=> Create Square of number from 1 to n

simple calculator.py
Please accept and merge my pull request sir/ma'am.
=> calculator using simple functions

A solution to project euler 49
Respected Sir/ma'am, plz accept and merge my pull request
=> Solution to project euler 49

Ocean_game.py
Reverts codehouseindia/Python-Programs#398
=> Revert "Update Ocean_game.py"

A solution to project euler 120
Respected sir/ma'am, plz accept and merge my pull request
=> Solution to project euler 120

Find HCF or GCD.py
this algorithm find HCF or GCD
=> Find HCF or GCD

KeyloggerMail.py, backdoor/client.py, backdoor/server.py
Key logger which send Screenshot,Keyboards strokes and Device details via mail
=> Keylogger.py

Dutch National Flag Algorithm
Python program to sort an array with   0, 1 and 2 in a single pass
=> Dutch National Flag Algorithm

transpose and flatten.py
I have added a python program named Transpose and Flatten using Numpy
=> Added Transpose and Flatten program

Lychrel Numbers.py
Here I have added the Lychrel Numbers problem solution using Python programming language
=> Added Lychrel Numbers

spiral traverse of matrix.py
python program which traverses the matrix in spiral form.
=> Created program to spiral traverse a matrix.

multiply three number in python
pls change last line,it will be k in place of t
=>  multiply three number in python

HarryPotterInvisibleCloak.py
This project uses Open CV technology to implement image manipulation and the invisibility effect.
=> Harry Potter Invisible Cloak

massIndex.py
This file has a python snippet code to calculate the body mass index.
=> Create the file to calculate body mass index

Isomorphic_graphs.py
Python Script to create and check whether two graphs are isomorphic or not.
=> Create Isomorphic_graphs.py - check for isomorphism

pigeonholesort.py
Pigeonhole sorting is a sorting algorithm that is suitable for sorting lists of elements where the number of elements and the number of possible key values are approximately the same.
=> added pigeonhole sort

A solution to project euler problem 06
Plz accept and merge my pull request sir/ma'am.
=> Solution to euler project problem 06

Styling improvements in euler project problem 10
Plz accept and merge my pull request
=> Styling improvements in euler project 10

Tower of Hanoi
=> Created tower of hanoi program.

Python sql table
Python mysql table
create table Employee (name varchar(20) not null, id int primary key, salary float not null, Dept_Id int not null)
=> Create Python sql table

Palindrome string program
=> Create Palindrome string program

Python Program to Sort Words in Alphabetic Order
Python Program to Sort Words in Alphabetic Order
=> Create Python Program to Sort Words in Alphabetic Order

merge.py, mergepython.py, sortmerge.py
=> Merge Sort in Python

guess.py
I just added a python file. I'd appreciate if it's accepted to help boost my PR to a reasonable stage on HacktoberFest.
=> added guess.py

variables.py
=> added variables

Sherlock and Anagrams
=> Create Sherlock and Anagrams

Array Manipulation
=> Create Array Manipulation

New Year Chaos
=> Create New Year Chaos

Armstrong Number.py
another method (or paradigm) to check for an Armstrong number in python
I have implemented using lists
please give it a try
=> Update Armstrong Number.py    using lists

Source Code to Merge Mails
=> Create Source Code to Merge Mails

Python Program to count the number of words in a text file
Given Python Program can be used  to count the number of words in a text file
=> Python Program to count the number of words in a text file

checkprime.py
Earlier time complexity was O(n)
but now with minor changes it is O(sqrt(n))
now large numbers can be easily checked in less time
=> Update checkprime.py    with less time complexity O( sqrt(n) )

Calculator
improved program using dictionaries and also has error handling for user input
=> Update Calculator using dictionaries also has error handling

BMI Calculator.py
This program shows the BMI based on the user input and also gives suggestions/comments based on the result.
=> Added the BMI Calculator program

Pdf_to_text.py
This python program will convert the given Pdf into text format.
=> Added Pdf to Text Convertor

vaishnav.py
Hey there,
I'm adding new Program from Hackerearth_Algorithms
=> Added Algorithm Program from Hackerearth

Tic_Tac_Toe.py
Can be played with two players.
FUN!!!!!!!!!
=> Added the TIC TAC TOE Game

Number_Guessing
Number Guessing Project using Python
=> Number_Guessing

pyramid.py
=> Created pyramid.py

RailwayReservationSystem in python.py
i created Railway Reservation system in python
i hope it will help to other programers
=> Create RailwayReservationSystem in python.py

edge_detection.py
=> Add image edge detection in python

Lossless-Text-Compression
Implemented huffman coding algorithm for lossless text compression using various data structures like hashmaps, trees, priority queues, and arrays in Python.
The compressed file is approximately 50% of the size of original file.
=> Lossless-Text-Compression

Remove Punctuation.py
A python program to remove punctuation from given sentance
=> Create Remove Punctuation.py

Find ASCII code
A python program to get ASCII value of given character
=> Create Find ASCII code

Python Program to Check Leap Year
Python Program to Check Leap Year program
=> Create Python Program to Check Leap Year
